# Generated by Django 3.1.1 on 2020-09-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('edad', models.IntegerField(default=10)),
                ('email', models.EmailField(default='ii@itsgg.edu.ec', max_length=254)),
                ('sexo', models.CharField(max_length=1)),
                ('estado', models.IntegerField(default=1)),
                ('user', models.CharField(max_length=15)),
                ('user_mod', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
                'db_table': 'tr_docente',
            },
        ),
    ]
